name: Build and Deploy
#on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  #push:
    #branches:
      #- main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: ğŸ’¾ Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: ğŸ”§ Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v2
      - name: ğŸ› ï¸ Install dependencies
        run: yarn install
      - name: ğŸ“¦ Build
        run: yarn run build
        env:
            CI: true
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Deploy branch
        uses: JamesIves/github-pages-deploy-action@3.7.1
        needs: test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        needs: test
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch